# Generated by Django 5.1.1 on 2024-10-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning_and_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=100),
        ),
    ]
