# Generated by Django 5.1.1 on 2024-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning_and_scheduling', '0003_remove_comment_task_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
