# Generated by Django 5.1.1 on 2024-10-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning_and_scheduling', '0005_project_created_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
