# Generated by Django 5.1.1 on 2024-11-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning_and_scheduling', '0002_initial'),
        ('project_planning_and_scheduling', '0006_remove_project_created_at_remove_project_updated_at'),
    ]

    operations = [
    ]
