# Generated by Django 5.1.1 on 2024-11-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning_and_scheduling', '0007_merge_20241105_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], max_length=6),
        ),
    ]
